// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// PENTING: Ganti file ini dengan output dari `flutterfire configure`
/// setelah kamu membuat Firebase project di https://console.firebase.google.com
///
/// Cara generate:
///   1. Buat project di Firebase Console
///   2. Jalankan: dart pub global run flutterfire_cli:flutterfire configure
///   3. File ini akan otomatis di-overwrite
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions belum dikonfigurasi untuk platform ini.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzYSKbt4RXBlHxqilMDLd8Qt2d79wVquo',
    appId: '1:191106536176:web:ddef5847c766d33818a835',
    messagingSenderId: '191106536176',
    projectId: 'fitnexa-app',
    authDomain: 'fitnexa-app.firebaseapp.com',
    storageBucket: 'fitnexa-app.firebasestorage.app',
  );

  // TODO: Ganti dengan konfigurasi Firebase Web kamu

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRWqCnWKTc-rRouJV9V1hobbVX_6OCWrU',
    appId: '1:191106536176:android:9e172e2a8ee94b4d18a835',
    messagingSenderId: '191106536176',
    projectId: 'fitnexa-app',
    storageBucket: 'fitnexa-app.firebasestorage.app',
  );

  // TODO: Ganti dengan konfigurasi Firebase Android kamu

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMrkdlY4rEMlFREsPdh5ecnxUHxhmsctc',
    appId: '1:191106536176:ios:6a05f5b6b6181cd718a835',
    messagingSenderId: '191106536176',
    projectId: 'fitnexa-app',
    storageBucket: 'fitnexa-app.firebasestorage.app',
    iosBundleId: 'com.example.uasfitnexa',
  );

  // TODO: Ganti dengan konfigurasi Firebase iOS kamu
}